version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:11
        steps:
            - checkout
            - run:
                name: install-dependencies
                command: npm install
            - run:
                name: tests
        test:
          docker:    
            - image: circleci/node:11  
          steps:
            - checkout
            - run:
                name: install-dependencies
                command: npm install
            - run:
                name: tests  
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
